version: '3.9'

services:

  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: cooking_core
      POSTGRES_USER: cooking_core
      POSTGRES_PASSWORD: cooking_core
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://cooking_core:cooking_core@db:5432/cooking_core

volumes:
  postgresql-data:
    driver: local
